// <auto-generated />
using System;
using Infrastructure.Helpers.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Helpers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230723113457_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Helpers.Models.BoilerPlateDb.Entity.tbl_BasicTest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tbl_BasicTest");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Country = "Bangladesh",
                            Name = "Sakib",
                            SysDate = new DateTime(2023, 7, 23, 17, 34, 57, 572, DateTimeKind.Local).AddTicks(3696)
                        },
                        new
                        {
                            id = 2,
                            Country = "USA",
                            Name = "John Doe",
                            SysDate = new DateTime(2023, 7, 23, 17, 34, 57, 572, DateTimeKind.Local).AddTicks(3708)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
